version: "3.9"
services:
  #POSTGRES SERVICE
  db:
    container_name: postgresql
    image: postgres:14-alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=012345678
      - POSTGRES_DB=gam3r.store
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network

  #PG ADMIN
  dbms:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=adm@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=01234567
    user: root
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - dev-network

# INTERNAL NETWORK
networks:
  dev-network:
    driver: bridge